version: '3.7'

# releases metadata (optional)
x-pathwar:
  challenge:
    name: "Image Board"
    slug: imageboard
    locale: "en"
    author: "Pathwar Staff"
    homepage: https://github.com/pathwar/pathwar/tree/master/challenges/web/imageboard
  flavor:
    purchase_price: 5
    validation_reward: 15
    body: "The passphrase is commented somewhere in the source."

services:
  front:
    build: front
    ports:
      - 80
    depends_on:
      - mysql

  mysql:
    build: mysql
    expose:
      - 3306
