version: '3.7'

x-pathwar:
  challenge:
    version: 1.0.0
    name: "Image Board"

services:
  front:
    build: front
    ports:
      - 80
    depends_on:
      - mysql

  mysql:
    build: mysql
    expose:
      - 3306
