version: '3.7'

# releases metadata (optional)
x-pathwar:
  challenge:
    name: "Upload Hi!"
    slug: upload-hi
    locale: "en"
    author: "Pathwar Staff"
    homepage: https://github.com/pathwar/pathwar/tree/master/challenges/web/upload-hi
  flavor:
    purchase_price: 5
    validation_reward: 15
    body: "Execute your code."
    passphrases: 1
    category: web
    tags:
      - exec
    redump-policy:
      - strategy: on-validation
      - strategy: every
        delay: 1d

services:
  front:
    build: front
    ports:
      - 80
