files:
  - source: /web/src/translations/en.json
    translation: /web/src/translations/%two_letters_code%.json
  - source: /challenges/web/upload-hi/front/translations/en_US/LC_MESSAGES/*.po
    translation: /challenges/web/upload-hi/front/translations/%locale_with_underscore%/LC_MESSAGES/%original_file_name%
