version: '3.3'

services:
  server:
    image: pathwar/pathwar:latest
    build: .
    entrypoint:
      - ./wait-for-it.sh
      - server-db:3306
      - "--"
    environment:
      - SQL_CONFIG=pathwar:uns3cur3@tcp(serverdb:3306)/pathwar?charset=utf8&parseTime=true
    command:
      - /bin/pathwar.pw
      - server
      - --http-bind=0.0.0.0:8000
      - --grpc-bind=0.0.0.0:9111
    depends_on:
      - serverdb
      - mailserver
    ports:
      - 8000:8000
      - 9111:9111

  web:
    build: web
    image: pathwar/pathwar:web
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - NODE_ENV=development
      - API_TARGET=server:8000
    links:
      - server

  keycloak:
    image: jboss/keycloak:6.0.1
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: uns3cur3
      DB_VENDOR: MYSQL
      DB_ADDR: keycloakdb
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: uns3cur3
    ports:
      - 8443:8443
    depends_on:
      - keycloakdb
      - mailserver

  serverdb:
    image: mariadb:10
    restart: always
    volumes:
      - serverdb_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: uns3cur3
      MYSQL_DATABASE: pathwar
      MYSQL_USER: pathwar
      MYSQL_PASSWORD: uns3cur3

  keycloakdb:
    image: mariadb:10
    restart: always
    volumes:
      - keycloakdb_data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: uns3cur3
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: uns3cur3

  mailserver:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  serverdb_data:
    driver: local
  keycloakdb_data:
    driver: local
