version: '2.3'

services:
  server:
    image: pathwar/pathwar:latest
    build: .
    entrypoint:
      - "/bin/bash"
      - "-c"
    command:
      - "./wait-for-it.sh mysql:3306 -- /bin/pathwar.pw server --sql-config='root:uns3cur3@tcp(mysql:3306)/pathwar?charset=utf8&parseTime=true' --http-bind=0.0.0.0:8000 --grpc-bind=0.0.0.0:9111"
    depends_on:
      - mysql
    ports:
      - 8000:8000
      - 9111:9111

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: uns3cur3
      MYSQL_DATABASE: pathwar

  web:
    build: web
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - NODE_ENV=development
      - API_TARGET=server:8000
    links:
      - server