version: '3.7'

services:
  pathwar-dev:
    image: pathwar/pathwar:latest
    restart: on-failure
    entrypoint:
      - ./wait-for-it.sh
      - db:3306
      - "--"
    environment:
      # specific to prod
      - VIRTUAL_HOST=api-dev.pathwar.land
      - VIRTUAL_PORT=8000
      # loaded from .env
      - ENGINE_URN
    command:
      - pathwar
      - --debug
      - engine
      - --urn=$ENGINE_URN
      - server
      - --http-bind=0.0.0.0:8000
      - --grpc-bind=0.0.0.0:9111
      # - --cors-allowed-origins=https://www.pathwar.land ## FIXME: enable in production
    depends_on:
      - db
      - mailserver
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - service-proxy
      - internal

  pathwar-unsafe:
    image: pathwar/pathwar:latest
    restart: on-failure
    entrypoint:
      - ./wait-for-it.sh
      - db:3306
      - "--"
    environment:
      # specific to prod
      - VIRTUAL_HOST=api-unsafe.pathwar.land
      - VIRTUAL_PORT=8000
      # loaded from .env
      - ENGINE_URN
    command:
      - pathwar
      - --debug
      - engine
      - --urn=$ENGINE_URN
      - --sso-unsafe
      - server
      - --http-bind=0.0.0.0:8000
      - --grpc-bind=0.0.0.0:9111
      # - --cors-allowed-origins=https://www.pathwar.land ## FIXME: enable in production
    depends_on:
      - db
      - mailserver
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - service-proxy
      - internal

  mailserver:
    image: fgribreau/smtp-to-sendgrid-gateway
    restart: on-failure
    ports:
      - 25:25
    environment:
      - SENDGRID_API
    networks:
      - internal

  db:
    image: mariadb:10
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_USER
      - MYSQL_DATABASE
    networks:
      - internal

volumes:
  db_data:
    driver: local

networks:
  service-proxy:
    external: true
  internal:
