version: '3.7'

services:
  agent-dev:
    image: pathwar/agent:latest
    restart: on-failure
    volumes:
      - ./data/:/data/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PATHWAR_AGENT_NGINX_DOMAIN_SUFFIX
      - PATHWAR_AGENT_NAME
      - PATHWAR_AGENT_NGINX_PORT
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    working_dir: /data/
    command:
      -   --debug
      - agent
      -   --salt=uns3cur3
      -   --moderator-password=uns3cur3
      -   --nginx-domain-suffix=$PATHWAR_AGENT_NGINX_DOMAIN_SUFFIX
      -   --agent-name=$PATHWAR_AGENT_NAME
      -   --port=$PATHWAR_AGENT_NGINX_PORT
      
      #   -agent-name localhost                                Agent Name
      #   -clean false                                         remove all pathwar instances before executing
      #   -delay 10s                                           delay between each loop iteration
      #   -docker-image docker.io/library/nginx:stable-alpine  docker image used to generate nginx proxy container
      #   -domain-suffix local                                 Domain suffix to append
      #   -host 0.0.0.0                                        Nginx HTTP listening addr
      #   -http-api-addr https://api-dev.pathwar.land          HTTP API address
      #   -moderator-password ...                              Challenge moderator password
      #   -nginx-domain-suffix local                           Domain suffix to append
      #   -once false                                          run once and don't start daemon loop
      #   -port 8001                                           Nginx HTTP listening port
      #   -salt ...                                            salt used to generate secure hashes (random if empty)
      #   -sso-clientid platform-cli                           SSO ClientID
      #   -sso-clientsecret ...                                SSO ClientSecret
      #   -sso-realm Pathwar-Dev                               SSO Realm
      #   -sso-token-file pathwar_agent_oauth_token.json       Token file
