version: '3.7'

# releases metadata (optional)
x-pathwar:
  challenge:
    name: "Training: Include"
    slug: training-include
    locale: "en"
    author: "Pathwar Staff"
    homepage: https://github.com/pathwar/pathwar/tree/master/challenges/web/training-include
  flavor:
    purchase_price: 0
    validation_reward: 5
    body: "Learn to execute custom code."
    passphrases: 1
    category: web
    tags:
      - tutorial
      - exec
    redump-policy:
      - strategy: on-validation
      - strategy: every
        delay: 1d

services:
  front:
    build: front
    ports:
      - 80
