version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APPLICATION_PORT=3310
      - DATABASE_URL=mysql://root:uns3cur3@localhost:3306/pathwar
      - DATABASE_SSL=false
      - FOREST_AUTH_SECRET=
      - FOREST_ENV_SECRET=
    ports:
      - "3310:3310"
    volumes:
      - ./:/usr/src/app
