version: 2

jobs:
  # lint:             # various linting
  # generate          # this job generates files ('make generate') and raise an error if the generated files are not the same as before
  # docker.images:    # this job builds docker images

  # build the project from within Docker, based on the Dockerfile
  docker.build:
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t pathwar/pathwar .
      # FIXME: save cache

  # build and unit test the project
  test:
    docker:
      - image: circleci/golang:1.12.4
    working_directory: /go/src/pathwar.pw
    environment:
      GOPATH: /go
      GO111MODULE: "on"
    steps:
      - checkout
      # FIXME: restore cache
      - run: go clean -modcache
      - run: go get
      - run: make _ci_prepare
      - run: make test
      # FIXME: setup coverage
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.12.2
      - run: PATH=$PATH:$(pwd)/bin make lint
      # FIXME: save cache
      # FIXME: store_test_results

  docker.integration:
    docker:
      - image: docker/compose:1.24.0
    steps:
      - checkout
      - run:
          name: Install Deps
          command: |
            apk --no-cache add curl openssl make bash
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t pathwar/pathwar .
      - run: docker build -t pathwar/pathwar:test ./test
      - run: make integration.run
      - run: make integration.run # yes, again
      - run: docker-compose logs

workflows:
  version: 2
  commit:
    jobs:
      - test
      - docker.build
      - docker.integration
