version: 2.1

orbs:
  moul: moul/build@1.9.0  # https://github.com/moul/build
  retry: moul/retry@0.6.0 # https://github.com/moul/retry

jobs:
  docker_integration:
    docker:
      - image: docker/compose:1.24.0
    steps:
      - checkout
      - retry/install
      - run: retry -m 3 apk --no-cache add curl openssl make bash
      - setup_remote_docker:
          docker_layer_caching: true
      - run: retry -m 3 make integration.build
      - run: retry -m 3 make integration.run
      - run: retry -m 3 make integration.run # yes, again :)
      - run: docker-compose logs

workflows:
  main:
    jobs:
      - moul/golang-build:
          gopkg: pathwar.land
          prepare-build: make _ci_prepare
      - moul/docker-build:
          image: pathwar/pathwar
      - docker_integration
