version: '3.7'

# releases metadata (optional)
x-pathwar:
  challenge:
    name: "Hello World!"
    slug: helloworld
    locale: "en"
    author: "Pathwar Staff"
    homepage: https://github.com/pathwar/pathwar/tree/master/challenges/web/helloworld
  flavor:
    purchase_price: 0
    validation_reward: 1
    body: "Introduction challenge."
    passphrases: 1
    category: web
    tags:
      - intro
    redump-policy:
      - strategy: every
        delay: 1d

services:
  front:
    build: front
    ports:
      - 80
