version: '3.3'

services:
  server:
    image: pathwar/pathwar:latest
    build: .
    entrypoint:
      - ./wait-for-it.sh
      - server-db:3306
      - "--"
    environment:
      - SQL_CONFIG=pathwar:uns3cur3@tcp(mysql:3306)/pathwar?charset=utf8&parseTime=true
    command:
      - /bin/pathwar.land
      - server
      - --http-bind=0.0.0.0:8000
      - --grpc-bind=0.0.0.0:9111
    depends_on:
      - mysql
      - mailserver
    ports:
      - 8000:8000
      - 9111:9111

  mysql:
    image: mariadb:10
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: uns3cur3
      MYSQL_DATABASE: pathwar
      MYSQL_USER: pathwar
      MYSQL_PASSWORD: uns3cur3

  mailserver:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  mysql_data:
    driver: local
