version: '3.7'

services:
  server:
    #image: pathwar/pathwar:latest
    build: ..
    restart: unless-stopped
    entrypoint:
      - /bin/bash
      - ./wait-for-it.sh
      - mysql:3306
      - "--"
    command:
      - /bin/pathwar
      - --debug
      - api
      - --sso-unsafe
      - server
      - --bind=0.0.0.0:8000
    links:
      - mailserver
    ports:
      - 8000
      - 9111

  zipkin:
    image: openzipkin/zipkin-slim:latest
    ports:
      - 9411

  mailserver:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - 1025
      - 8025
