version: "2"

services:
  nginx-proxy:
    restart: unless-stopped
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/conf.d"
      - "./vhost.d:/etc/nginx/vhost.d:ro"
      - "/usr/share/nginx/html"
      - "./volumes/certs:/etc/nginx/certs:ro"
    networks:
      - service-proxy
      
  letsencrypt-nginx-proxy-companion:
    restart: unless-stopped
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/certs:/etc/nginx/certs:rw"
      - ./vhost.d:/etc/nginx/vhost.d

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.${HOST_DOMAIN_SUFFIX}
      - LETSENCRYPT_HOST=whoami.${HOST_DOMAIN_SUFFIX},${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL
    depends_on:
      - nginx-proxy
      - letsencrypt-nginx-proxy-companion
    networks:
      - service-proxy

networks:
  service-proxy:
    external: true
    