version: '3.7'

# releases metadata (optional)
x-pathwar:
  challenge:
    name: "Training: Sqli"
    slug: training-sqli
    locale: "en"
    author: "Pathwar Staff"
    homepage: https://github.com/pathwar/pathwar/tree/master/challenges/web/training-sqli
  flavor:
    purchase_price: 0
    validation_reward: 5
    body: "Learn to execute custom code."
    passphrases: 2
    category: web
    tags:
      - tutorial
      - sql
      - injection
    redump-policy:
      - strategy: every
        delay: 1d

services:
  front:
    build: front
    ports:
      - 80
    depends_on:
      - mysql

  mysql:
    build: mysql
    expose:
      - 3306
