version: '3.7'

services:
  front:
    image: pathwar/training-sqli:front
    build: front
    ports:
      - 80
    depends_on:
      - mysql

  mysql:
    image: pathwar/training-sqli:mysql
    build: mysql
    expose:
      - 3306
