[build]
  base = "web/"
  publish = "public"
  command = "npm install && npm run build"
  ignore = "git diff --quiet HEAD^ HEAD -- ."

[build.environment]
  YARN_FLAGS = "--no-ignore-optional"
  API_URL = "https://api.pathwar.land/"
  KEYCLOAK_REALM = "Pathwar-Dev"
  KEYCLOAK_BASE_URL = "https://id.pathwar.land/"

[context.production.environment]
  API_URL = "https://api.pathwar.land/"
  KEYCLOAK_REALM = "Pathwar-Dev"
  KEYCLOAK_BASE_URL = "https://id.pathwar.land/"
